# Spektralnorm einer Diagonalmatrix

$$
A = \begin{pmatrix}
    0 &0 &0 &0 &0 \\
    0 &8 &0 &0 &0 \\
    0 &0 &-5 &0 &0 \\
    0 &0 &0 &-3 &0 \\
    0 &0 &0 &0 &-3 \\
\end{pmatrix} \Rightarrow ||A||_2 = ?
$$

In [18]:
import numpy as np

diagonal_elemente = [4, 0, 7, -3, 1]
A = np.diag(diagonal_elemente)
print(A)

[[ 4  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  7  0  0]
 [ 0  0  0 -3  0]
 [ 0  0  0  0  1]]


In [19]:
np.linalg.norm(A, 2)

7.0

$$
||A||_2 = \sqrt{\lambda_{\operatorname{max}}(A^{\operatorname{T}}A)}
$$

$A$ ist Diagonalmatrix $\Rightarrow ||A||_2 =$ betragsmäßig größtes Diagonalelement