# Singulärwertzerlegung

Jede Matrix $A\in\mathbb{R}^{n\times m}$ lässt sich als $A=U\Sigma V^{\operatorname{T}}$ schreiben, wobei $U\in\mathbb{R}^{n\times n}$, $V\in\mathbb{R}^{n\times n}$ orthogonale Matrizen sind und $\Sigma\in\mathbb{R}^{n\times m}$ eine Diagonalmatrix ist.

Bestimmen Sie die **Singulärwertzerlegung** der Matrix $$A=\begin{pmatrix} -1 &-8 \\ -4 &4 \end{pmatrix}.$$

*Hinweis*: Zur Rechnung "von Hand" nutzen Sie, z.B. die Eigenwerte und Eigenvektoren der Matrix $AA^{\operatorname{T}}$ um die Singulärwerte und einen Satz Singulärvektoren (rechts oder links) zu erhalten. Überlegen Sie sich, wie man den anderen Satz Singulärwerte daraus erhält.

Gesucht: $A = U\Sigma V^{\operatorname{T}} = (~~)(~~)(~~)$

In [6]:
import numpy as np
np.set_printoptions(precision=4)

A = np.array([[-1, -8], [-4, 4]])

In [19]:
U, S, VT = np.linalg.svd(A)

print(U)
print(np.diag(S))
print(VT)

[[-0.8682  0.4961]
 [ 0.4961  0.8682]]
[[9. 0.]
 [0. 4.]]
[[-0.124   0.9923]
 [-0.9923 -0.124 ]]


In [41]:
# Probe
USVT = U @ np.diag(S) @ VT
print(USVT, '= USVT')

print('USVT == A:', np.allclose(USVT, A))

[[-1. -8.]
 [-4.  4.]] = USVT
USVT == A: True
