## Aufgabe 2a: Lineare Kleinste-Quadrate, Regularisierung, Iterative Lösung

In [6]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)

x1 = np.array([-1, 2, 5, 6, 7, -2])
x2 = np.array([4, 9, 5, -2, 1, -1])
y = np.array([-19, 73, 149, 160, 191, -54])

### Kleinste-Quadrate

In [3]:
n = x1.shape[0]

A = np.vstack([np.ones(n), x1, x2]).T
print(A)

[[ 1. -1.  4.]
 [ 1.  2.  9.]
 [ 1.  5.  5.]
 [ 1.  6. -2.]
 [ 1.  7.  1.]
 [ 1. -2. -1.]]


In [7]:
W = np.linalg.lstsq(A, y, rcond=None)[0]
print(W)

[ 1.3347 27.0629  1.9952]


### Tikhonov

In [10]:
mu = 0.14
m = 3       # 3 Gewichte

y_snake = np.concatenate((y, np.zeros(m)))
X_snake = np.vstack([A, np.sqrt(mu) * np.eye(m)])

print(X_snake)
print(y_snake)

[[ 1.     -1.      4.    ]
 [ 1.      2.      9.    ]
 [ 1.      5.      5.    ]
 [ 1.      6.     -2.    ]
 [ 1.      7.      1.    ]
 [ 1.     -2.     -1.    ]
 [ 0.3742  0.      0.    ]
 [ 0.      0.3742  0.    ]
 [ 0.      0.      0.3742]]
[-19.  73. 149. 160. 191. -54.   0.   0.   0.]


In [11]:
W_snake = np.linalg.lstsq(X_snake, y_snake, rcond=None)[0]
print(f'W~0 = {W_snake[0]:.4f}, W~1 = {W_snake[1]:.4f}, W~2 = {W_snake[2]:.4f}')

W~0 = 1.4357, W~1 = 27.0173, W~2 = 1.9932


### Gradientenabstieg

In [12]:
def gd_landweber(X, y, w_0, alpha, max_iter):
    w_k = w_0
    print(f'0: w_k = {w_k}')
    for k in range(1, max_iter + 1):
        w_k = w_k - alpha * X.T @ (X @ w_k - y)
        print(f'{k}: w_k = {w_k}')
    return w_k

In [13]:
w_0 = np.array([1, 0, 0]).T
alpha = 0.001
max_iter = 5

W_landweber = gd_landweber(A, y, w_0, alpha, 5)

0: w_k = [1 0 0]
1: w_k = [1.494 3.298 1.235]
2: w_k = [1.9092 6.1507 2.1853]
3: w_k = [2.2582 8.6226 2.9046]
4: w_k = [ 2.5516 10.7686  3.4373]
5: w_k = [ 2.7982 12.635   3.8198]
