In [1]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)

x1 = np.array([6, 6, 4, 1, 3, 0])
x2 = np.array([1, 2, 1, 2, -1, 2])
y = np.array([45, 55, 31, 15, 8, 3])

w0 = np.array([-4, 7, 4, 0])
alpha = 0.01

j = [6, 3, 1, 4, 5, 2]

In [2]:
n = y.size

# Ausgleichsmatrix
A = np.vstack([np.ones(n), x1, x2, x1 * x2]).T
print(A)

[[ 1.  6.  1.  6.]
 [ 1.  6.  2. 12.]
 [ 1.  4.  1.  4.]
 [ 1.  1.  2.  2.]
 [ 1.  3. -1. -3.]
 [ 1.  0.  2.  0.]]


In [4]:
def gradient(w, X, y):
    y_hat = X @ w
    return X.T @ (y_hat - y)

def sgd(w0, X, y, grad_fun, max_it, rate, perm=None):
    w = w0
    n = X.shape[0]
    
    for k in range(max_it):
        idx = perm or np.random.permutation(n)
        print(k + 1, 'idx:', idx)

        for i in idx:
            xi = np.array([X[i - 1]])
            yi = np.array([y[i - 1]])
            grad = grad_fun(w, xi, yi)
            w = w - rate * grad
        print(k + 1, 'W:', w)
    
    return w

In [5]:
W = sgd(w0, A, y, grad_fun=gradient, max_it=1, rate=alpha, perm=j)

1 idx: [6, 3, 1, 4, 5, 2]
1 W: [-3.9503  7.2798  4.2002  0.7866]
